# Site settings
title:       What I Think About When I Think About Engineering
email:       
author:      Mike Smith
description: "Thoughts on life as a software engineer"
baseurl:     ""
url:         "https://kerumai.com"
date_format: "%b %-d, %Y"

# Google services
google_analytics: UA-17664632-2
google_verification: qlI4QHowIiDF7jhvrJvwVfSKhZ1g7kcPb4rBgWpuntw

# Optional features
animated:             false
show_related_posts:   false
show_post_footers:    false
show_social_icons:    true
ajaxify_contact_form: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: kerumai

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments: 
facebook_appid: 
facebook_comments_number: 10

# Social icons
github_username: kerumai
bitbucket_username:
stackoverflow_id:
twitter_username: kerumai
google_plus_id:
linkedin_username: kerumai
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: true
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
gems:
  - jekyll-paginate


jekyll-crosspost_to_medium:
  enabled: true
  cache: .jekyll-crosspost_to_medium
  status: draft
  license: all-rights-reserved
  text: '<p><i>This article was originally posted on my own site <a href=\"#{url}\" rel=\"canonical\">kerumai.com</a>.</i></p>'
